shellEmulator: true

trustPolicy: no-downgrade

allowBuilds:
  "@nestjs/core": true
  "@prisma/engines": true
  prisma: true
  unrs-resolver: true
overrides:
  chokidar: 3.6.0
onlyBuiltDependencies:
  - "*"
